### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/PPE-GSB#1]
Liste des choses à faire :
- [x]  Repenser la base Access : 
  - [x] Point de vue visiteur @ZeroAbsolu 
  - [x] Point de vue délégué + responsable
- [ ] Transférer la base sur MySQL
- [ ] Adapter la maquette HTML pour pouvoir la générer avec du PHP
- [ ]  Créer un système de login
- [ ] Sécuriser l'accès + validation des inputs
- [ ]  Lier les pages HTML à la base de donnée avec le PHP
- [ ] Rendre le site responsive ( bonus)
- [ ] Installer le serveur sur la banana PI 
- [ ] Documenter : 
  - [ ] Procédures
  - [ ] Présentation PowerPoint
  - [ ] "Bibliographie" ( Framework...etc)
